# Permalinks
permalink:           "/:title"

#Nav Pages List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Setup
title:               Sanket Kumar Gautam
tagline:             SKG
url:                 https://sanketgautam.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sanket Kumar Gautam
  url:               https://twitter.com/sanketkgautam
  email:             sk2gautam@gmail.com

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/sanketgautam/sanketgautam.github.io

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
